CREATE USER tudor WITH ENCRYPTED PASSWORD 'tudor';
GRANT ALL PRIVILEGES ON DATABASE postlib TO tudor;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tudor;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tudor;